### ISSUE TITLE
BackgroundAudioService系のエラー

### ISSUE THREAD

**Issue by Takesikaityo** [Ogiwara-CostlierRain464/Aileen#1]
03-31 17:49:13.221 1216-1216/? D/StatusBar: Clicked on button 0 for 0|jp.ogiwara.java.aileen|1|null|10409
03-31 17:49:13.231 15613-15613/? I/jp.ogiwara.java.aileen.service.BackgroundAudioService: handleIntent#pause
03-31 17:49:13.261 15613-15613/? D/AndroidRuntime: Shutting down VM
03-31 17:49:13.261 15613-15613/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: jp.ogiwara.java.aileen, PID: 15613
                                                   java.lang.NullPointerException: Attempt to read from field 'java.lang.String jp.ogiwara.java.aileen.model.YouTubeVideo.title' on a null object reference
                                                       at jp.ogiwara.java.aileen.service.BackgroundAudioService.buildNotification(BackgroundAudioService.java:154)
                                                       at jp.ogiwara.java.aileen.service.BackgroundAudioService.access$300(BackgroundAudioService.java:37)
                                                       at jp.ogiwara.java.aileen.service.BackgroundAudioService$3.onPause(BackgroundAudioService.java:121)
                                                       at android.support.v4.media.session.MediaSessionCompat$Callback$StubApi21.onPause(MediaSessionCompat.java:847)
                                                       at android.support.v4.media.session.MediaSessionCompatApi21$CallbackProxy.onPause(MediaSessionCompatApi21.java:195)
                                                       at android.media.session.MediaSession$CallbackMessageHandler.handleMessage(MediaSession.java:1329)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5290)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:737)

**Comment by Ogiwara-CostlierRain464** [comment]
ありがとうございます

ヌルポだったとは
もう面倒だから次はKotlinで書こう()

**Comment by Takesikaityo** [comment]
тнайк чoμ_〆(･ω･* )
